.TH "TANGLE\-NEW\-PLUGIN" "" "February 2014" "" ""
.SH "NAME"
\fBtangle-new-plugin\fR
.QP
.P
A tangle plugin for managing tangle plugins

.
.SH Usage
.SS Global configuration
.P
If these config values are set, they will be used as defaults\.
.P
.RS 2
.EX
$ tangle config \-k user:name \-v "Your name"
$ tangle config \-k user:email \-v "you@example\.com"
$ tangle config \-k user:url \-v "http://yourhomepage\.example"
$ tangle config \-k user:github:username \-v \'yourUsername\'
.EE
.RE
.SS Creating your plugin
.P
.RS 2
.EX
$ mkdir tangle\-myplugin
$ cd tangle\-myplugin

$ tangle new\-plugin
# \.\.\.
.EE
.RE
.SS Editing your plugin
.P
.RS 2
.EX
$ npm link
$ grunt watch # Automatically rebuild & test on file change events
.EE
.RE
.SS Publishing your plugin
.P
.RS 2
.EX
$ npm publish
$ npm unlink
$ npm install tangle\-myplugin \-g
.EE
.RE