.TH "TANGLE\-PLUGIN" "" "March 2014" "" ""
.SH "NAME"
\fBtangle-plugin\fR
.QP
.P
A tangle plugin for managing tangle plugins

.
.SH OVERVIEW
.P
tangle \fIhttps://github\.com/tanglejs/tangle\fR is a set of tools
for building web applications\.
.P
A TangleJS plugin is any npm module that includes \'tangle\-plugin\' in the
keywords array of its package\.json\.
.P
Unlike Bower components or other npm modules, plugins are extensions to the
TangleJS system, not to your projects\. Most plugins provide some additional
subcommand of \fBtangle\fR for you to work with\.
.SH USAGE
.P
.RS 2
.EX
\-\-option, \-o [String] \- An example option\.
\-\-help, \-h \- Display this message
.EE
.RE