#!/usr/bin/env node
path = require('path');

exports.command = {
  description: '<%= plugin.description %>',
  arguments: null // Optional arguments string to display
};

if (require.main === module) {
  require(path.join(__dirname, '..', 'index.js'));
}
